# Terminal
set -g default-terminal "tmux-256color"

# History
set -g history-limit 50000

# Escape time
set -sg escape-time 200

# Vi keys
set -g mode-keys vi

# Mouse
set -g mouse on

# Base index
set -g base-index 1
set -g pane-base-index 1

# Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Focus events
set -g focus-events on

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux.conf"

# vim-tpipeline
# Plugins (via TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'vimpostor/vim-tpipeline'

set -g @ukiyo-theme 'kanagawa/dragon'

set -g @ukiyo-status-left ""
set -g @ukiyo-status-right ""

set -g status-left ""
set -g status-right ""
set -g status-style bg=default
set -g status-left-length 99
set -g status-right-length 99

# Inactive Windows: Teal (Aoi) pill with Highlight body
setw -g window-status-format "#[fg=#7aa89f,bg=#1f1f28]#[fg=#16161d,bg=#7aa89f]#I#[fg=#7aa89f,bg=#2a2a37]#[fg=#dcd7ba,bg=#2a2a37] #W #[fg=#2a2a37,bg=#1f1f28]"

# Active Window: Insert Green pill with Highlight body
setw -g window-status-current-format "#[fg=#93a261,bg=#1f1f28]#[fg=#16161d,bg=#93a261,bold]#I#[fg=#93a261,bg=#2a2a37]#[fg=#dcd7ba,bg=#2a2a37,bold] #W #[fg=#2a2a37,bg=#1f1f28]"

# Ensure spacing and centering for tpipeline
setw -g window-status-separator "  "
set -g status-justify centre

run '~/.tmux/plugins/tpm/tpm'

